### ISSUE TITLE
Creating Menus with Builder

### ISSUE THREAD

**Issue by Xliff** [japhb/Terminal-Widgets#1]
I tried [creating a menu](https://github.com/Xliff/Terminal-Widgets/blob/main/examples/form-menu.raku), and the menu is not showing. What am I missing?

Thanks

**Comment by japhb** [comment]
Hi there!  Thanks for filing the issue.

You had one bug: on line 34, you should have a comma instead of a semicolon.  This bug was causing your menu definition to get sunk away.

While I was looking at your example, I realized you were trying to use the Menu widget in a very minimal way, so I enhanced the Menu widget a few ways:

- Support minimal config without error
- Support override of hint-delivery target
- Provide a gist method that will give better debug info

I haven't cut a new release yet, since I would like your feedback and you're using a Git fork anyway, rather than installing from the ecosystem.  You should be able to pull from my upstream and have it working better for you now.  :slightly_smiling_face:
