### ISSUE TITLE
Adding Colored Labels

### ISSUE THREAD

**Issue by Xliff** [japhb/Terminal-Widgets#3]
Is this currently possible with Terminal::Widgets?

**Comment by japhb** [comment]
If you mean a *single* color style then yes; see https://github.com/japhb/Terminal-Widgets/blob/main/lib/Terminal/Widgets/PlainText.rakumod -- anything acceptable by Terminal::ANSIColor would be accepted as the "color" there.  I use this to make the hints for my menus italic; see https://github.com/Raku-MUGS/MUGS-UI-TUI/blob/main/lib/MUGS/App/TUI/MainMenu.rakumod#L151-L156 for an example of that.

If you mean arbitrarily complex sub-span styling, well -- at the moment that would be rather hackish.  It's on my short list, because it's an excuse to be able to handle rendering spans of HTML-like complexity, but hadn't risen to the top previously.  Is this what you're looking for?

**Comment by Xliff** [comment]
I'm looking more for the latter, really. Does T::P have support for RGB text, yet?

**Comment by japhb** [comment]
> I'm looking more for the latter, really.

Ah, OK, that'll take me a bit to make work, but maybe this is a good excuse to work on that.  :-)

> Does T::P have support for RGB text, yet?

Literally anything Terminal::ANSIColor supports, which includes 3-, 4-, 8-, and 24-bit color schemes (for foreground and background), plus attributes of various sorts.  See the upper left and upper center of one of the test images in the https://github.com/japhb/Terminal-Tests README, and you'll see what I mean.

The difference between what it supports _now_ and what you seem to _want_ is that right now **both** color and layout styles are per-widget, not per-character-cell.  The underlying library (Terminal::Print) is fully capable of per-character-cell drawing, but I hadn't implemented that yet at the higher layers.  That's part of what I need to implement -- as well as a decently brief way of _specifying_ that level of style detail without it becoming a complete markup mess.

**Comment by japhb** [comment]
I realized there's another piece of this problem that is in my head, but wasn't mentioned above:  I want all of this to work well with string localization *and* style theming in a half-decent way, so that e.g. a French translator faced with having the word `not` specified to have a "super-emphasized" style -- which might for one user be "uppercase bold white on red" and for another might be "underlined italic" -- can specify that `ne` and `pas` should share that same style marking, but not (necessarily) the word in the middle.

**Comment by Xliff** [comment]
OK, so to sum it up , it looks like I can have a label, with 24-bit color and a common style across all cells of that label.

What would creating one of these look like in code?

Thanks!

**Comment by japhb** [comment]
I added an example for you: https://github.com/japhb/Terminal-Widgets/blob/main/examples/styles.raku

Does that help?

**Comment by japhb** [comment]
As of 0.0.10, I believe the new `examples` scripts cover enough **existing** SGR styling functionality to use it reasonably.

I've split the more advanced parts of this (adding per-span and per-cell styling) into new issue #4 , so closing this one.
