### ISSUE TITLE
Request see a pdf page and be able to scroll around it and change viewing distance

### ISSUE THREAD

**Issue by tbrowder** [japhb/Terminal-Widgets#7]
Being able to select pages would be very helpful.

**Comment by tbrowder** [comment]
Low res should be fine. My main use case would be looking at pdf text documents while away from my Linux PC or laptop. I do lots of pdf creation while logged in remotely through app Termius on my iPad. I'm also too lazy to leave my arm chair to check my work station.

I apreciate all you do for the Raku community!

**Comment by japhb** [comment]
> Low res should be fine. My main use case would be looking at pdf text documents while away from my Linux PC or laptop. I do lots of pdf creation while logged in remotely through app Termius on my iPad. I'm also too lazy to leave my arm chair to check my work station.

*chuckle*

OK, so it sounds like your use case is just checking that your PDF creation pipeline actually produced something parseable, with approximately the correct content in it?

> I apreciate all you do for the Raku community!

Why thank you!  :-)

**Comment by japhb** [comment]
**(Summary: It's complicated.  I'm sure you're surprised by this.  :wink:)**

The problem is that most terminals are limited to displaying a fixed set of glyphs on cell boundaries, with a default terminal window typically being 80 by 24 cells.  So while each glyph can be rendered beautifully with dozens of pixels by the font server -- which makes the **text** crisp and clear these days -- you can't actually **address** those pixels individually within the terminal in order to draw with them.

You can get individual color control over two "blocks" per cell, because ANSI/VT terminals can only deal with one foreground and one background color, and Unicode provides a half-cell block glyph where one half is the foreground color and the other is the background.  That trick is typically used to make the terminal show 80 x 48 square blocks.  It's better than a Tamagotchi display for sure ... but probably not much past late-1970s home computer.

You can make ultimate use of this trick by telling your terminal to use the smallest font you possibly can and then maximizing the terminal window.  If you've got a big enough hi-res monitor and a really tiny font (e.g. 3x6 pixels per glyph) you can get an approximation of a real low-res screen.  On my 30" 4K desk monitor that gets me a terminal window with 1275x598 virtual pixel "resolution", which is fun for drawing Mandelbrot sets, and reminds me a bit of a wider-format version of a late-1980s CRT resolution (800x600 "SVGA" graphics being a common size at the time).

To get past even that barrier you have to give up on full color control, once again because of the limitations of the ANSI/VT color model.  One such trick is drawing with Braille glyphs, using the individual dots to form shapes.  This gets you 2x4 "pixels" per terminal cell, which is twice the resolution in both directions that the half-cell block glyph gets you -- though because Braille dots are not space-filling, it looks a bit like you're looking through a screen door at your drawing.  And going back to the "one background color" problem, all the space _between_ the dots is necessarily the same color as an "off pixel".

For what it's worth this technique is not only used by a fair number of terminal graphing libraries -- the [Braille topic at GitHub]( https://github.com/topics/braille) shows 213 projects at the moment -- it's actually been used in the blind community as well; instructions for doing this kind of drawing _by hand_ exist at places like https://sixdotsart.com/ and https://www.brailleart.org/en/braille-drawings.html .

A variant of this uses the "sextant" blocks from the [Symbols for Legacy Computing Unicode block](https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing).  On the plus side, the sextant blocks are space-filling, so no bleeding of the background color between the foreground "pixels".  On the minus side, they're only 2x3 instead of 2x4, and current fonts can't agree if they should be one or two cells wide -- which also means the "pixels" aren't square, but they aren't square _two different ways_, without an easy way to test for it (without just asking the user, of course).

Past that there are a few special cases that are usable -- a very modern terminal emulator and font can use that same Symbols for Legacy Computing set to draw one vertical or horizontal line per cell at 8-per-cell resolution -- but again the problem of font width confusion still exists, and lots of things want more complex drawing options than single lines per cell.

So there's your complicated answer -- it all depends on how much generality you're willing to sacrifice to get resolution, but even then there are limits.  And dang, you better have a great terminal emulator and font to work with if you want to try the more advanced tricks!

**Comment by tbrowder** [comment]
On Wed, Jan 31, 2024 at 17:14 Geoffrey Broadwell ***@***.***>
wrote:

> *(Summary: It's complicated. I'm sure you're surprised by this. 😉)*
>
Ok, I knew some of that, I guess I was hoping for some modern magic.

I'll close the issue, sorry for the noise.

Blessing,

-Tom

**Comment by tbrowder** [comment]
Closed as an impossible task

**Comment by japhb** [comment]
A *few* terminals have support for drawing primitives in the data stream, but unfortunately that doesn't include the most common terminal packages.  Some emulators like `xterm` have optional support for some ancient formats, but it's not compiled into the default builds, so most users won't even know it's there as an option.

So barring use of (and special support for) a particular rarer terminal, what I said before is about what you can find widely supported.
